### ISSUE TITLE
Filter workflows by name

### ISSUE THREAD

**Issue by ulfsauer0815** [fortis-it-services/actio#10]
**Is your feature request related to a problem? Please describe.**
We want to use the dashboard in our daily routine (SPoC) to see where failures need attention, but it tends to be littered with irrelevant workflows/failures
examples for important failures: main build, deployments, security checks
examples for irrelevant failures: pull request builds (they are red all the time, but can be ignored)

**Describe the solution you'd like**
We would like to be able to filter which workflows to show/hide.
Maybe as an exclude and/or include filter (contains by name).
exclude: PR,staging
include: deploy,build

**Describe alternatives you've considered**
Have a dashboard configuration file in each repo (e.g. actio.yml), which defines configuration profiles  with filter options etc.
Just dreaming here :wink:

**Comment by kschlesselmann** [comment]
@ulfsauer0815 Sounds like a valid suggestion to me. I just drafted some code to filter repository names by substring. Please have a look and tell me if this is heading in the correct direction.

As far as I see you'd like to specify multiple repository names. For that I'd enable some kind of RegEx mode for the name filter in an upcoming commit.

Regarding your alternative: IMHO it would be too much to actually consider the repository content in actio but maybe we can come up with some special repository labels for that? Something like `#actio:workflow-names:Foo,Bar` … but I'm just dreaming as well ;-)

**Comment by ulfsauer0815** [comment]
@kschlesselmann Yeah, that looks like the right direction! :)

I'd like to provide a list of (keyword, patterns, regex), so I can filter by workflow names and see only those that match _any_ of the patterns ("I only want to see workflows that include "build" _or_ "deploy")
and I'd like to exclude workflows with names that match _any_ of the patterns

So I think the config could like something like (assuming keywords):
include: build,deploy
exclude: staging,pull request

or with patterns
include: *build*,*deploy*
exclude: *staging*,*pull request*

Maybe regular expressions can eliminate the need to provide a list, but sometimes it gets difficult to express _or_ conditions on whole words etc., so I think a list is still the better option (comma-separated or otherwise)

**Comment by kschlesselmann** [comment]
@ulfsauer0815 Sounds great. In the meantime we had the discussion about the complexity of RegEx as well and decided to go with a list of patterns as well. For usability we try to use [Chips](https://material.angular.io/components/chips/overview) which provide a nice way to configure multiple patterns. I think we'll introduce this feature today/start of next week. Stay tuned :-)

**Comment by xorph** [comment]
@ulfsauer0815 we just released version 1.1.0 with filtering for workflow names. For now we only support include patterns, but we have a plan to support excludes as well. :-)

**Comment by ulfsauer0815** [comment]
Just tried it and works as expected! Awesome! :smiley:

**Comment by kschlesselmann** [comment]
Perfect :-)
